# Generated by Django 6.0.2 on 2026-04-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('borrower', 'Borrower')], default='borrower', max_length=20),
        ),
    ]
