# Generated by Django 6.0.3 on 2026-05-16 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0002_borrowing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, choices=[('Romance', 'Romance'), ('Fantasy', 'Fantasy'), ('Science Fiction', 'Science Fiction'), ('Historical Fiction', 'Historical Fiction'), ('Networking & Systems Administration', 'Networking & Systems Administration'), ('Programming & Software Development', 'Programming & Software Development'), ('Other', 'Other')], default='Other', max_length=100, null=True),
        ),
    ]
